In [12]:
import numpy as np

# Define Sigmoid
def sigmoid(x, deriv=False):
    if(deriv==True):
        # Derivative of Sigmoid, using the Chain Rule. X is the sigmoid function itself.
        return x*(1-x)
    return 1/(1+np.exp(-x))

# Dataset
x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
y = np.array([[0],
              [1],
              [1],
              [0]])

# Seed
np.random.seed(1)

# 3 Layer 16 param NN

# Initialize weights
syn0 = 2 * np.random.random((3,4)) - 1  # 3 rows of 4 params
syn1 = 2 * np.random.random((4,1)) - 1  # 4 rows of 1 param

EPOCHS = 10000

# Train
for i in range(EPOCHS):
    
    # Feed forward
    l0 = x  # Input layer 4x3
    l1 = sigmoid(np.dot(l0,syn0))  # Hidden layer matrix multiplication: 4x3 * 3x4 = 4x4
    l2 = sigmoid(np.dot(l1,syn1))  # Output layer: 4x4 * 4x1 = 4x1

    l2_error = y - l2  # Difference error
    l2_delta = l2_error * sigmoid(l2,True)  # Output's derivative on Sigmoid -> Confidence: NOT DOT-PRODUCT 4x1 * 4x1 = 4x1

    if (i% (EPOCHS/5)) == 0:
        print('Error:' + str(np.mean(np.abs(l2_error))))
    
    # Update weights
    syn1 += np.dot(l1.T,l2_delta)  # Direct update based on each input's "role" in the answer (their value)

    # Backpropogation (update weights for next layer)
    l1_error = np.dot(l2_delta,syn1.T)  # Use weights to determine how layer 2's error should be factored into the 0th synapse
    l1_delta = l1_error * sigmoid(l1,True)
    syn0 += np.dot(l0.T,l1_delta)
    
    

print(syn0)
print(syn1)

Error:0.4964100319027255
Error:0.024100331782672454
Error:0.014989371383758006
Error:0.011632678090062791
Error:0.00978619559085451
[[ 4.06042771  3.77082949 -6.07912135 -3.91610434]
 [-1.93040092 -5.51443521 -6.38988281 -3.20582466]
 [ 0.58045944 -1.83622119  2.41599928  5.24917117]]
[[-6.01608689]
 [ 6.37578506]
 [-9.6324098 ]
 [ 6.90846291]]
