In [15]:

import numpy as np

# Define sigmoid
def sigmoid(x, deriv=False):
    if(deriv==True):
        # Derivative of Sigmoid. X is the sigmoid function itself.
        return x*(1-x)
    return 1/(1+np.exp(-x))


x = np.array([
    [1, 0, 0, 1],
    [1, 1, 0, 1],
    [1, 0, 1, 1],
    [0, 1, 0, 1]
])

y = np.array([
    [1],
    [1],
    [0],
    [0]
])

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights0   = np.random.rand(self.input.shape[1],4)
        self.weights1   = np.random.rand(4,4) 
        self.weights2   = np.random.rand(4,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer0 = sigmoid(np.dot(self.input, self.weights0))
        print(self.layer0)
        self.layer1 = sigmoid(np.dot(self.layer0, self.weights1))
        print(self.layer1)
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        print(self.output)

    def backprop(self):
        self.error = (self.y - self.output) ** 2
        
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2 * (self.y - self.output) * sigmoid(self.output, True)))
        d_weights1 = np.dot(self.layer0.T,  (np.dot(2 * (self.y - self.output) * sigmoid(self.output, True), self.weights2.T) * sigmoid(self.layer1, True)))      
        
        # sigmoid(self.layer0, True), self.input.T, (self.weights1.T, sigmoid(self.output, True), 2*(self.y - self.output)), sigmoid(self.layer1, True), self.weights1.T
        print(2 * (self.y - self.output) * sigmoid(self.output, True), self.weights1.T)
#         print('weights', self.weights2)
#         print('asdf', np.dot(self.layer1, self.weights2))
#         print('dloss', 2 * (self.y - self.output))
        print('shapes', np.dot(self.weights1.T, 2 * (self.y - self.output) * sigmoid(self.output, True)).shape)
        print(sigmoid(self.layer1, True).shape)
        dcost_over_dlayer0 = np.dot(np.dot(np.dot(self.weights1.T, 2 * (self.y - self.output) * sigmoid(self.output, True)), sigmoid(self.layer1, True)), d_weights1)
        print('dcost', dcost_over_dlayer0)
#         d_weights0 = np.dot(self.input.T, (np.dot()))
        
        # update the weights with the derivative (slope) of the loss function
#         self.weights0 += d_weights0
        self.weights1 += d_weights1
        self.weights2 += d_weights2
        
TestNN = NeuralNetwork(x, y)

EPOCHS = 1
for i in range(EPOCHS):
    
    TestNN.feedforward()
    TestNN.backprop()
    
    if i % 200 == 0:
        print(np.mean(TestNN.error))
    

[[0.73768669 0.81102241 0.70143986 0.84109706]
 [0.82307884 0.83958906 0.79225218 0.84704797]
 [0.77507991 0.86285761 0.86421606 0.87901243]
 [0.7321206  0.71023129 0.74524549 0.72058545]]
[[0.87539044 0.85631736 0.80330989 0.84177383]
 [0.89254861 0.86872195 0.81808479 0.85802036]
 [0.8967058  0.86861085 0.82629963 0.85733722]
 [0.86795784 0.83657054 0.79013604 0.82824398]]
[[0.82949977]
 [0.83340416]
 [0.83463905]
 [0.82570253]]
[[ 0.04822766]
 [ 0.04626089]
 [-0.23038827]
 [-0.23766668]] [[0.81323258 0.75967259 0.82963071 0.18015314]
 [0.83125613 0.96993493 0.03792214 0.42633422]
 [0.24306276 0.71859512 0.58785559 0.27662073]
 [0.95503885 0.87341572 0.22277584 0.12167787]]
weights [[0.3098843 ]
 [0.50047672]
 [0.94781415]
 [0.14357902]]
asdf [[1.5820862 ]
 [1.60994797]
 [1.61886867]
 [1.55547116]]
dloss [[ 0.34100046]
 [ 0.33319167]
 [-1.66927809]
 [-1.65140507]]
shapes (4, 1)
(4, 4)


ValueError: shapes (4,1) and (4,4) not aligned: 1 (dim 1) != 4 (dim 0)